# Generated by Django 5.1.6 on 2025-02-19 09:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0002_alter_lecture_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='subjects',
            field=models.ManyToManyField(blank=True, to='admin_app.subject'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.today),
        ),
    ]
