# Generated by Django 5.1.6 on 2025-02-19 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0003_student_subjects_alter_lecture_date'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('student', 'lecture')},
        ),
    ]
