# Generated by Django 5.1.6 on 2025-02-21 19:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0005_alter_attendance_status_attendancefaculty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancefaculty',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
