# Generated by Django 5.1.6 on 2025-03-27 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0006_alter_attendancefaculty_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='image',
            field=models.ImageField(default='https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-chat/ava3.webp', upload_to='photos/'),
        ),
        migrations.AddField(
            model_name='student',
            name='image',
            field=models.ImageField(default='https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-chat/ava3.webp', upload_to='photos/'),
        ),
    ]
