# Generated by Django 5.1.6 on 2025-03-27 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0007_faculty_image_student_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='image',
            field=models.ImageField(default='ava3.jpg', upload_to='photos/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.ImageField(default='ava3.jpg', upload_to='photos/'),
        ),
    ]
